export const heroNames = {
  all: "Any hero selection",
  none: "No hero selection",
  archmage: "Archmage",
  alchemist: "Goblin Alchemist",
  avatarofflame: "Firelord",
  bansheeranger: "Dark Ranger",
  beastmaster: "Beastmaster",
  blademaster: "Blademaster",
  cryptlord: "Crypt Lord",
  deathknight: "Death Knight",
  demonhunter: "Demon Hunter",
  dreadlord: "Dread Lord",
  farseer: "Farseer",
  keeperofthegrove: "Keeper of the Grove",
  lich: "Lich",
  mountainking: "Mountain King",
  paladin: "Paladin",
  pandarenbrewmaster: "Pandaren Brewmaster",
  pitlord: "Pit Lord",
  priestessofthemoon: "Priestress of the Moon",
  seawitch: "Naga Sea Witch",
  shadowhunter: "Shadow Hunter",
  sorceror: "Bloodmage",
  taurenchieftain: "Tauren Chieftain",
  tinker: "Goblin Tinker",
  warden: "Warden"
};
